service: node-js-backend
name: yandex-cloud-template
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: yandex-cloud
  runtime: nodejs12-preview

plugins:
  - serverless-yandex-cloud

package:
  exclude:
    - ./**
  include:
    - 'node_modules/axios/**'
    - 'node_modules/cheerio/**'
    # Для парсинга и axios
    - 'node_modules/follow-redirects/**'
    - 'node_modules/htmlparser2/**'
    - 'node_modules/entities/**'
    - 'node_modules/domhandler/**'
    - 'node_modules/domelementtype/**'
    - 'node_modules/parse5/**'
    - 'node_modules/domutils/**'
    - 'node_modules/inherits/**'
    - 'node_modules/boolbase/**'
    - 'node_modules/lodash/**'
    - 'node_modules/css-what/**'
    - 'node_modules/nth-check/**'
    - 'node_modules/util-deprecate/**'
    - 'node_modules/string_decoder/**'
    - 'node_modules/readable-stream/**'
    - 'node_modules/css-select/**'
    - 'node_modules/dom-serializer/**'

    - 'lambda.js'

functions:
  api:
    handler: lambda.handler
    memory: 128
    timeout: 5

resources:
  trigger-sa:
    type: yc::ServiceAccount
    roles:
      - serverless.functions.invoker
